### PR TITLE
virtualenv cleanup stage completed

### PR DESCRIPTION
**Pull request by ciubotaru**

### CODE REVIEW

**Comment by vtexier** [comment]
**Warning :**

**--clear option on the virtualenv will remove the lib folder containing all the installed packages !**

After that, you have to redo all the install process again to run a build !

I don't think anybody want to do that...

**I think we should remove the deactivate part of the readme.**

People who want to exit virtualenv can close the shell and start a new one...

**Comment by galuel** [comment]
Ok, perhaps we could so alert of two ways to continue, one not using the --clear and the other one to remove all the installed packages.

**Comment by ciubotaru** [comment]
> --clear option on the virtualenv will remove the lib folder containing all the installed packages !

I assume that README is for final users, i.e. for someone who wants to create the set of cards, print them out and start playing. If my assumption is correct, then once the build is over, the user does not need virtualenv any more. Anyway, a good README should explain how to install software, how to use it and how to uninstall it when it's not needed.

**Comment by vtexier** [comment]
> I assume that README is for final users

I don't agree with your assumption.
Final users just use the web site, download and print cards from it.
They don't have to know github at all to do that.

Github is the code repository for contributors, so git knowledge is required, and here, python, sphinx and virtualenv as well.
So the readme just have to help to install the code for contributors, who kneed to complete many builds to test the code.

**Comment by ciubotaru** [comment]
> Final users just use the web site, download and print cards from it.

Only if they can read French. I failed on that. I just saw the link to github and decided to download from here. After I followed all steps from README, I realized that I've just produced another copy of the website. Then I deleted the build environment, and thought that everybody else would do the same. Hence my commit.

> I don't agree with your assumption.

Well, it's your project, so if you disagree with something, then this "something" is wrong :-)

**Comment by vtexier** [comment]
> Only if they can read French.
We will put online an english version of the web site. Asap !

**Pull request merged**
